name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: latest
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Build Website
        run: pnpm build
      - name: Upload Build Result
        uses: actions/upload-artifact@v3
        with:
          name: juegas-ajedrez
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download Build Result
        uses: actions/download-artifact@v3
        with:
          name: juegas-ajedrez
          path: ./dist
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
